export const FETCH_SINGLE_USERS_REQUEST = 'FETCH_SINGLE_USERS_REQUEST'
export const FETCH_SINGLE_USERS_SUCCESS = 'FETCH_SINGLE_USERS_SUCCESS'
export const FETCH_SINGLE_USERS_FAILURE = 'FETCH_SINGLE_USERS_FAILURE'